twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_3_layout.html.twig']

    paths:
        # pointe vers votre dossier d'images
        '%kernel.project_dir%/public/assets/images': images

when@test:
    twig:
        strict_variables: true
